MCU_FAMILY = MIMXRT1062
MCU_SERIES = MIMXRT1062
MCU_LDSCRIPT = MIMXRT1062
MCU_STARTUP = MIMXRT1062
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=FALSE
BOARD = IC_TEENSY_4_1
MCU = cortex-m4
ARMV = 7

# Custom
CAPS_WORD_ENABLE = yes
#AUTO_SHIFT_ENABLE = yes
REPEAT_KEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

# Bootloader selection
BOOTLOADER = halfkay

FIRMWARE_FORMAT = hex
